#!/usr/bin/env bash 
#getmir
while IFS=: read -r username password_placeholder uid gid gecos home_dir shell; do
echo "The user $username  is part of the $gid  gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $password_placeholder, more info about the user here: $gecos"
done < /etc/passwd 
